---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: identity
  name: ldap-data
  labels:
    app: openldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

