apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-rootuser-secret
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgA7CiWAhm3nKtn+m8q2F21HyYlbVcn6KpM/3onUrFxl7674PmWE02KM+r5V7kDk/J1l51RTeTuPSsoDtJkAWnAFrm6ADtv7EY6tV9IuSw8gJsMg+vLXvgxbBpAeR+Qn9GQ7qQ4i0NG9jiAfNk+9R0HvAj/ukf3GertPZ2Jba6Y7MbHXGgj62mhNnvDILnT9WA1GXjRv+OJMKw6ZBGYJLH0kPP4BjyFq+GjLYsQP7loTJL03cn+4K+MMJeMJaS41gWL/O/zC7FENzD7esSqHnF5F+BCKB84HJZ/uxCK/WRNQu+RIAbMJHZJgZOZitIVzm+WLDpMySk7sieUXD0/DbFgtMgLs2z+iCeeLBb0oGZuEBGkLEo0QiuWwyfgRqpf4+BqUm8R91nsgZAn767T8ls8OKDPCUdLDkmd1HvwfHQ/cn6LLoR6COiv3Yu5dxhRXUbCdUfQz6KQXdd9PBv27DR4E/0Z39P5+K4jM3gDs1MqhLscgz7TctC5NZQEn7oeOAw+cFODiWDchYcahOUC3o4QxFOqFJEhJXUYHeZx8svzgnQy1TGgKManNVpJ94oifls41vqNJhwvnAkGeMdDAOAl9ilAjwg54evaO3vGgJJo4i9omDRx1yrrcvC2Hc+f4jvIzCl15dlyD06CZAiPOJUcw0yM6ykDIaNfBwOWNtZRI0+agcw8AnRaCmssXxDYfW7huqC04IeA1OYrlmZOGoEQmIM8RPCfWynz6xPNda4sOde7SnSCWOP2sji1WS9PJ7+e14zBKFI041KfaIX/tOIlUPsCtkyLfc1xratQ5htNuXA==
    rootUser: AgCcc8EnaBpKnM8Y9WzAT1nHt53db+MrQg7d+f19Q4gjxfkn7NKcc/ux1PdnJ5K/Tc9N9+1pxrIqr9/yQzuOgWPsP6Bm+d8JcilDVOzR8uWBYrivazTpOLuE3Zj8HdGOsyNeZ4zCBD/j45ExPiCyowR50NXZ1wdhx56NGnCwuzCz4uGqJaAQ5hCJkevb2WDAh7ASlzBXT7sRv+h7/6McxkhrsJV4JRdu5vz0Y+PQRPzPdF3SDxhd7gmGNsXoU5zuXhKp41tkl/7YSyrXk5kfS2JCR/Akot0XOSv0F0b0t6oT3WcuZCUA1XKf86TBEF3r/ZkHLyXNwCq+9mQhI0wh7k6f0j35ofTn5ksXRKlHATfGvCCYovq5ojVwFK/dVEI6/4rwiMiRO1pqKIBSPEi+wn/tnqtE1J5yrH1mGE0OMvKiE99zFPw7FLrItSLzQhNxRQLCMwMdkMQSzwFIghHw+L0DPUVIp/LIqry52aAWeNqiTaVCpwPyZ1y/9fVRuhsFj3zFEqwF/DaDFTjpy8Hj09PZmbZ/cgjDbJ2gkzv/0o3Tu8Aym9ZvTOq009Nf7SRl+DYnfOT1eowN0iZc6/PSeAYkuIUxUe9JI/Sz6XqXxzokAGIBXw58TX2oaUtryFgorvHvy7HRjr5Cl5p64Uu4PBQ41FQmguzL6wV9c3JBh7TSOreptN8ugDXNqwQt/0FnkwwRRC+bivn9Q+vDZz2TyLz2quaKX6Hb7Cdpe0QpARRQpOy5W5E=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: minio-rootuser-secret
      namespace: minio
