kind: Job
apiVersion:  batch/v1
metadata:
  namespace: minio
  generateName: mc-alias-list-
spec:
  template:
    metadata:
      labels:
        app: minio
    spec:
      restartPolicy: Never
      containers:
        - name: mc-alias-list
          image: minio/mc
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: minio-root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: minio-root-password
          command: ["mc"]
          args: ["alias", "list", "--debug"]
          volumeMounts:
            - name: minio-config
              mountPath: "/root/.mc"
      volumes:
        - name: minio-config
          persistentVolumeClaim:
            claimName: minio-config    
