apiVersion: v1
data:
  minio-root-password: d2R2YjVydGdobjc2eXVqbQ==
  minio-root-user: QUNDRVNTS0VZRVhBTVBMRTEyMw==
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
