---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
  namespace: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-app
    app.kubernetes.io/version: "5.7.21"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: app
    app.kubernetes.io/managed-by: manually
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi