# Generate with 
# DBNAME=<database-name> 
# DBUSER=<database-user>
# DBUSERPASSWORD=<database-user-password>
# kubectl create secret generic mysql-secrets -n mysql \
#   --from-literal=MYSQL_RANDOM_ROOT_PASSWORD=true \
#   --from-literal=MYSQL_ONETIME_PASSWORD=true \
#   --from-literal=MYSQL_DATABASE=$DBNAME \
#   --from-literal=MYSQL_USER=$DBUSER \
#   --from-literal=MYSQL_PASSWORD=$DBUSERPASSWORD \
#   --dry-run=client -o yaml \
#   | tee mysql-1-replica-02-mysql-secrets.yaml
