# ROOTPASSWD=r00tpa55w0rd
# kubectl create secret generic mysql-root-password -n mysql \
#   --from-literal=MYSQL_ROOT_PASSWORD=$ROOTPASSWD \
#   --dry-run=client -o yaml \
#   | tee mysql-1-replica-02-mysql-root-secret.yaml
apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: cjAwdHBhNTV3MHJk
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql-root-password
  namespace: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-app
    app.kubernetes.io/version: "8.0"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: app
    app.kubernetes.io/managed-by: manually