---
kind: Job
apiVersion:  batch/v1
metadata:
  labels:
      app: velero-cli
  namespace: velero-cli
  name: velero-cli-install
spec:
  template:
    metadata:
      labels:
        app: velero-cli
    spec:
      serviceAccount: velerocli
      restartPolicy: Never
      containers:
        - name: velero-cli-install
          image: docker.io/xaviaznar/velero-cli:1.5.3
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: velero-install-config
          command: ["/bin/sh"]
          args: ["-c", "velero install --provider $PROVIDER --plugins $PLUGIN --bucket $BUCKET --backup-location-config region=minio,s3ForcePathStyle='true',s3Url=$BACKUP_LOCATION_CONFIG_URL --use-volume-snapshots=false --secret-file /tmp/minio-credentials"]
          volumeMounts:
            - name: cm-file-minio-credentials
              mountPath: /tmp/
      volumes:
        - name: cm-file-minio-credentials
          configMap:
            name: minio-credentials
