---
kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: greeter
spec:
  params:
    - name: subject
      type: string
  steps:
    - name: greeter
      image: alpine:3.13
      command:
        - echo
      args:
        - "Hello "
        - "$(params.subject)"
