---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 1.16.1
    helm:
      releaseName: sealed-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets