---
kind: Namespace
apiVersion: v1
metadata:
    name: monitoring
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: prometheus
rules:
    - apiGroups: [""]
      resources:
        - nodes
        - services
        - endpoints
        - pods
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - extensions
      resources:
        - ingresses
      verbs:
        - get
        - list
        - watch
---
kind: ServiceAccount
apiVersion: v1
metadata:
    name: prometheus
    namespace: monitoring
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: monitoring
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: 30s # Tailor to your cluster's needs
    scrape_configs:
      - job_name: 'kubelet'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true # Required with Minikube
      - job_name: 'cadvisor'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true # Required with Minikube
        metrics_path: /metrics/cadvisor
      - job_name: 'k8sapiserver'
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true # Required with Minikube
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_service_name
            - __meta_kubernetes_enpdpoint_port_name
            action: keep
            regex: default;kubernetes;https
      - job_name: 'k8services'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_service_name
            action: drop
            regex: default;kubernetes
          - source_labels:
            - __meta_kubernetes_namespace
            action: keep
            regex: default
          - source_labels:
            - __meta_kubernetes_service_name
            target_label: job
      - job_name: 'k8spods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
            - __meta_kubernetes_pod_container_port_name
            action: keep
            regex: metrics
          - source_labels:
            - __meta_kubernetes_pod_container_name
            target_label: job
